version: '3.3'

services:
  # nginx:
  #   container_name: GS-back-nginx
  #   build:
  #     context: .
  #     dockerfile: docker/nginx.Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - nodejs
  nodejs:
    entrypoint: [sh, -c, 'npm run dev']
    hostname: 'nodejs'
    container_name: GS-back-srv
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    ports:
      - 3000:3000
    links:
      - pgdb:pgdb
    volumes:
      - ./:/var/www/granite/
    extra_hosts:
      - 'smtp.yandex.ru:77.88.21.158'
  pgdb:
    image: postgres:alpine
    container_name: GS-back-pgdb
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
